# SPDX-License-Identifier: GPL-2.0
TEST_GEN_PROGS := tracing_ns_smoke tracing_bpf_userns_smoke
TEST_PROGS := tracing_ns_control_path.sh tracing_bpf_userns_control.sh \
	 kernfs_filter_reload_visibility.sh
CFLAGS += -Wall -Werror
include ../lib.mk
