/* SPDX-License-Identifier: GPL-2.0-only */
#ifndef _LINUX_VPSADMINOS_LIVEPATCH_BUILD_H
#define _LINUX_VPSADMINOS_LIVEPATCH_BUILD_H

/* Overwritten by the vpsAdminOS livepatch artifact builder. */
#ifndef LIVEPATCH_ORIG_KERNEL_VERSION
#define LIVEPATCH_ORIG_KERNEL_VERSION	"6.12.95"
#endif
#ifndef LIVEPATCH_NAME
#define LIVEPATCH_NAME			"0"
#endif
#ifndef LIVEPATCH_ARTIFACT_ROLE
#define LIVEPATCH_ARTIFACT_ROLE		"boot-kernel"
#endif
#ifndef LIVEPATCH_IS_GUARD
#define LIVEPATCH_IS_GUARD		0
#endif
#ifndef LIVEPATCH_IS_CHECKPOINT_GUARD
#define LIVEPATCH_IS_CHECKPOINT_GUARD	0
#endif
#ifndef LIVEPATCH_IS_REVERSE_GUARD
#define LIVEPATCH_IS_REVERSE_GUARD	0
#endif
#ifndef LIVEPATCH_IS_FOUNDATION
#define LIVEPATCH_IS_FOUNDATION		0
#endif
#ifndef LIVEPATCH_IS_GENERATION_FINAL
#define LIVEPATCH_IS_GENERATION_FINAL	0
#endif
#ifndef LIVEPATCH_IS_CHECKPOINT
#define LIVEPATCH_IS_CHECKPOINT		0
#endif
#ifndef LIVEPATCH_EXPECTED_FUNCTIONS
#define LIVEPATCH_EXPECTED_FUNCTIONS	0
#endif
#ifndef LIVEPATCH_GUARD_FUNCTIONS
#define LIVEPATCH_GUARD_FUNCTIONS	4
#endif
#ifndef LIVEPATCH_ANCHOR_FUNCTIONS
#define LIVEPATCH_ANCHOR_FUNCTIONS	204
#endif
#ifndef LIVEPATCH_FOUNDATION_FUNCTIONS
#define LIVEPATCH_FOUNDATION_FUNCTIONS	0
#endif
#ifndef LIVEPATCH_FINAL_FUNCTIONS
#define LIVEPATCH_FINAL_FUNCTIONS	1
#endif
#ifndef LIVEPATCH_INVENTORY_ID_HI
#define LIVEPATCH_INVENTORY_ID_HI	0ULL
#endif
#ifndef LIVEPATCH_INVENTORY_ID_LO
#define LIVEPATCH_INVENTORY_ID_LO	0ULL
#endif
#ifndef LIVEPATCH_ANCHOR_INVENTORY_ID_HI
#define LIVEPATCH_ANCHOR_INVENTORY_ID_HI	0ULL
#endif
#ifndef LIVEPATCH_ANCHOR_INVENTORY_ID_LO
#define LIVEPATCH_ANCHOR_INVENTORY_ID_LO	0ULL
#endif
#ifndef LIVEPATCH_GUARD_INVENTORY_ID_HI
#define LIVEPATCH_GUARD_INVENTORY_ID_HI	0ULL
#endif
#ifndef LIVEPATCH_GUARD_INVENTORY_ID_LO
#define LIVEPATCH_GUARD_INVENTORY_ID_LO	0ULL
#endif
#ifndef LIVEPATCH_FOUNDATION_INVENTORY_ID_HI
#define LIVEPATCH_FOUNDATION_INVENTORY_ID_HI	0ULL
#endif
#ifndef LIVEPATCH_FOUNDATION_INVENTORY_ID_LO
#define LIVEPATCH_FOUNDATION_INVENTORY_ID_LO	0ULL
#endif
#ifndef LIVEPATCH_FINAL_INVENTORY_ID_HI
#define LIVEPATCH_FINAL_INVENTORY_ID_HI	0ULL
#endif
#ifndef LIVEPATCH_FINAL_INVENTORY_ID_LO
#define LIVEPATCH_FINAL_INVENTORY_ID_LO	0ULL
#endif

#ifdef __GENKSYMS__
/*
 * Keep exported symbol CRCs tied to the base 6.12.95 livepatch core API.
 * The artifact builder overwrites these macros per generated module, but that
 * release-specific metadata must not leak into genksyms' view of exported
 * symbols.
 */
#undef LIVEPATCH_ORIG_KERNEL_VERSION
#define LIVEPATCH_ORIG_KERNEL_VERSION	"6.12.95"
#undef LIVEPATCH_NAME
#define LIVEPATCH_NAME			"0"
#undef LIVEPATCH_ARTIFACT_ROLE
#define LIVEPATCH_ARTIFACT_ROLE		"boot-kernel"
#undef LIVEPATCH_IS_GUARD
#define LIVEPATCH_IS_GUARD		0
#undef LIVEPATCH_IS_CHECKPOINT_GUARD
#define LIVEPATCH_IS_CHECKPOINT_GUARD	0
#undef LIVEPATCH_IS_REVERSE_GUARD
#define LIVEPATCH_IS_REVERSE_GUARD	0
#undef LIVEPATCH_IS_FOUNDATION
#define LIVEPATCH_IS_FOUNDATION		0
#undef LIVEPATCH_IS_GENERATION_FINAL
#define LIVEPATCH_IS_GENERATION_FINAL	0
#undef LIVEPATCH_IS_CHECKPOINT
#define LIVEPATCH_IS_CHECKPOINT		0
#undef LIVEPATCH_EXPECTED_FUNCTIONS
#define LIVEPATCH_EXPECTED_FUNCTIONS	0
#undef LIVEPATCH_GUARD_FUNCTIONS
#define LIVEPATCH_GUARD_FUNCTIONS	4
#undef LIVEPATCH_ANCHOR_FUNCTIONS
#define LIVEPATCH_ANCHOR_FUNCTIONS	204
#undef LIVEPATCH_FOUNDATION_FUNCTIONS
#define LIVEPATCH_FOUNDATION_FUNCTIONS	0
#undef LIVEPATCH_FINAL_FUNCTIONS
#define LIVEPATCH_FINAL_FUNCTIONS	1
#undef LIVEPATCH_INVENTORY_ID_HI
#define LIVEPATCH_INVENTORY_ID_HI	0ULL
#undef LIVEPATCH_INVENTORY_ID_LO
#define LIVEPATCH_INVENTORY_ID_LO	0ULL
#undef LIVEPATCH_ANCHOR_INVENTORY_ID_HI
#define LIVEPATCH_ANCHOR_INVENTORY_ID_HI	0ULL
#undef LIVEPATCH_ANCHOR_INVENTORY_ID_LO
#define LIVEPATCH_ANCHOR_INVENTORY_ID_LO	0ULL
#undef LIVEPATCH_GUARD_INVENTORY_ID_HI
#define LIVEPATCH_GUARD_INVENTORY_ID_HI	0ULL
#undef LIVEPATCH_GUARD_INVENTORY_ID_LO
#define LIVEPATCH_GUARD_INVENTORY_ID_LO	0ULL
#undef LIVEPATCH_FOUNDATION_INVENTORY_ID_HI
#define LIVEPATCH_FOUNDATION_INVENTORY_ID_HI	0ULL
#undef LIVEPATCH_FOUNDATION_INVENTORY_ID_LO
#define LIVEPATCH_FOUNDATION_INVENTORY_ID_LO	0ULL
#undef LIVEPATCH_FINAL_INVENTORY_ID_HI
#define LIVEPATCH_FINAL_INVENTORY_ID_HI	0ULL
#undef LIVEPATCH_FINAL_INVENTORY_ID_LO
#define LIVEPATCH_FINAL_INVENTORY_ID_LO	0ULL
#endif

#if LIVEPATCH_IS_CHECKPOINT_GUARD && !LIVEPATCH_IS_GUARD
#error "a checkpoint guard must also select the guard role"
#endif
#if LIVEPATCH_IS_REVERSE_GUARD && !LIVEPATCH_IS_GUARD
#error "a reverse guard must also select the guard role"
#endif
#if LIVEPATCH_IS_CHECKPOINT_GUARD && LIVEPATCH_IS_REVERSE_GUARD
#error "checkpoint and reverse guard modes are distinct artifacts"
#endif
#if (LIVEPATCH_IS_GUARD + LIVEPATCH_IS_FOUNDATION + \
	LIVEPATCH_IS_GENERATION_FINAL + LIVEPATCH_IS_CHECKPOINT) > 1
#error "at most one livepatch artifact role may be selected"
#endif

#endif /* _LINUX_VPSADMINOS_LIVEPATCH_BUILD_H */
